# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: 
  displayName: 'Run a one-line script'

- task: NodeTool@0 
  inputs:
    versionSpec: '12.x' # replace this value with the version that you need for your project

- script: npm install -g typescript

- script: bash taydenna.sh
  workingDirectory: src

- script: tsc
  workingDirectory: src

- script: cp index.html dist/
  workingDirectory: src

- script: cp tietoja.html dist/
  workingDirectory: src

- script: cp testi.html dist/
  workingDirectory: src

- script: cp mvp.css dist/
  workingDirectory: src
